# Python Introduction

In [1]:
print("Hello world!");

Hello world!


Python uses indentation for blocks, instead of curly braces. Both tabs and spaces are supported, but the standard indentation requires standard Python code to use four spaces. 

In [2]:
x = 1
if x == 1:
    print("x is 1")

x is 1


# Variables and Types

Python is completely object oriented, and not "statically typed". You do not need to declare variables before using them, or declare their type. Every variable in Python is an object.

- Numbers
-- integers
-- floating point
-- (complex numbers)
- Strings

In [3]:
myfloat = 7.0
print(myfloat)
myfloat = float(7)
print(myfloat)

7.0
7.0


In [4]:
mystring = 'hello'
print(mystring)
mystring = "hello"
print(mystring)
mystring = "let's play a game"
print(mystring)

one = 1
two = 2
three = one + two
print(three)

hello = "hello"
world = "world"
helloworld = hello + " " + world
print(helloworld)

hello
hello
let's play a game
3
hello world


In [5]:
a, b = 3, 4
print(a, b)

3 4


In [6]:
astring = "Hello World!"
print(len(astring))
print(astring.count("l"))
print(astring[3:7])
print(astring[3:7:2]) # start:stop:step
print(astring[::-1])
print(astring.upper())
print(astring.lower())
print(astring.startswith("Hello"))
print(astring.split(" "))

12
3
lo W
l 
!dlroW olleH
HELLO WORLD!
hello world!
True
['Hello', 'World!']


# List
Lists are very similar to arrays. They can contain any type of variable, and they can contain as many variables as you wish. Lists can also be iterated over in a very simple manner. Here is an example of how to build a list.

In [7]:
list1 = [1, 2, 3]
mylist = []
mylist.append(1)
mylist.append(2)
mylist.append(3)

print(mylist[0])
print(mylist[1])
print(mylist[2])

for x in mylist:
    print(x)

1
2
3
1
2
3


In [8]:
languages = ["Python", "Swift", "C++"]
print(languages[-1])
print(languages[-2])
print(languages[-3])

C++
Swift
Python


## Slicing a List

In [9]:
my_list = ['p','r','o','g','r','a','m','i','z']
print(my_list[2:5])
print(my_list[5:])
print(my_list[:])


['o', 'g', 'r']
['a', 'm', 'i', 'z']
['p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z']


In [10]:
languages = ['Python', 'Swift', 'C++', 'C', 'Java', 'Rust', 'R']
del languages[1]
print(languages)

languages = ['Python', 'Swift', 'C++', 'C', 'Java', 'Rust', 'R']
del languages[-1]
print(languages)

languages = ['Python', 'Swift', 'C++', 'C', 'Java', 'Rust', 'R']
del languages[0:2]
print(languages)

['Python', 'C++', 'C', 'Java', 'Rust', 'R']
['Python', 'Swift', 'C++', 'C', 'Java', 'Rust']
['C++', 'C', 'Java', 'Rust', 'R']


In [11]:
languages = ['Python', 'Swift', 'C++']

for language in languages:
    print(language)

Python
Swift
C++


In [12]:
languages = ['Python', 'Swift', 'C++']

print('C' in languages)    # False
print('Python' in languages)    # True

False
True


## List Comprehension

In [13]:
numbers = [number * number for number in range(1, 6)]
print(numbers)

[1, 4, 9, 16, 25]


# Basic Operators

In [14]:
number = 1 + 2 + 3 / 4.0
print(number)

remainder = 11 % 3
print(remainder)

squared = 7 ** 2
cubed = 2 ** 3
print(squared)
print(cubed)

3.75
2
49
8


## String Operators

In [15]:
helloworld = "hello " + "world"
print(helloworld)

hello = "hello"
print(hello + str(5))

print(hello * 10)

hello world
hello5
hellohellohellohellohellohellohellohellohellohello


## List Operators

In [16]:
even_numbers = [2,4,6,8]
odd_numbers = [1,3,5,7]

print(even_numbers + odd_numbers)

print([1,2,3] * 5)

[2, 4, 6, 8, 1, 3, 5, 7]
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


## String Formatting

In [17]:
name = "John"
age = 23
print("%s is %d years old." % (name, age))

John is 23 years old.


# Conditions

In [18]:
x = 2
print(x == 2) # prints out True
print(x == 3) # prints out False
print(x < 3) # prints out True

name = "John"
age = 23
if name == "John" and age == 23:
    print("Your name is John, and you are also 23 years old.")

if name == "John" or name == "Rick":
    print("Your name is either John or Rick.")

True
False
True
Your name is John, and you are also 23 years old.
Your name is either John or Rick.


In [19]:
name = "John"
if name in ["John", "Rick"]:
    print("Your name is either John or Rick.")

Your name is either John or Rick.


In [20]:
statement = False
another_statement = True
if statement is True:
    print("A")
elif another_statement is True: # else if
    print("B")
else:
    print("C")

B


In [21]:
x = [1,2,3]
y = [1,2,3]

print (x == y)
print (x is y)

True
False


In [22]:
print (not False)
print ((not False) == False)

True
False


# Loops

## For

In [23]:
primes = [2, 3, 5, 7]
# 2 is the oddest prime

for prime in primes:
    print(prime)
    
for x in range(5):
    print(x)
    
for x in range(3, 6):
    print(x)

for x in range(3, 8, 2):
    print(x)

2
3
5
7
0
1
2
3
4
3
4
5
3
5
7


## While

In [24]:
count = 0
while count < 5:
    print(count)
    count += 1

0
1
2
3
4


In [25]:
count = 0
while True:
    print(count)
    count += 1
    if count >= 5:
        break

# Prints out only odd numbers - 1,3,5,7,9
for x in range(10):
    # Check if x is even
    if x % 2 == 0:
        continue
    print(x)

0
1
2
3
4
1
3
5
7
9


## Else?!
Unlike languages like C,CPP.. we can use else for loops. When the loop condition of "for" or "while" statement fails then code part in "else" is executed. If a break statement is executed inside the for loop then the "else" part is skipped. Note that the "else" part is executed even if there is a continue statement.

In [26]:
count=0
while(count<5):
    print(count)
    count +=1
else:
    print("count value reached %d" %(count))

0
1
2
3
4
count value reached 5


# Functions

In [27]:
def my_function():
    print("Hello From My Function!")
    
def my_function_with_args(username = "Stefan", greeting = "a nice evening"):
    print("Hello, %s , From My Function!, I wish you %s"%(username, greeting))

In [28]:
my_function_with_args("Karim", "a nice day")
my_function_with_args(greeting = "a nice day", username = "Karim")
my_function_with_args("Karim")
my_function_with_args()

Hello, Karim , From My Function!, I wish you a nice day
Hello, Karim , From My Function!, I wish you a nice day
Hello, Karim , From My Function!, I wish you a nice evening
Hello, Stefan , From My Function!, I wish you a nice evening


## Lambdas

In [29]:
greet = lambda : print("Hello World")

greet()

greet_user = lambda name : print('Hey there,', name)
greet_user("Felix")

Hello World
Hey there, Felix


# Global and Local Variables

In [30]:
def greet():
    message = "Hello"
    print("From Function: ", message)
    
greet()
print(message)

From Function:  Hello


NameError: name 'message' is not defined

In [ ]:
message_global = "Hello"

def greet2():
    print("From Function: ", message_global)
    
greet()
print(message_global)

In [ ]:
c = 1

def add():
    print(c)
    c = c + 1
    
add()
add()
add()

In [ ]:
c = 1

def add():
    global c
    print(c)
    c = c + 1
    
add()
add()
add()

# Classes and Objects

In [ ]:
class MyClass:
    variable = "blah"
    
    def function(self):
        print(self.variable) #vergl. this.variable in java
        print("Hello from MyClass:Function")

myobjectx = MyClass()
print(myobjectx.variable)
print(myobjectx.function())

In [ ]:
class Numberholder:

    def __init__(self, number): # constructor
        self.number = number
        
    def getNumber(self):
        return self.number

myobjectx = Numberholder(7)
print(myobjectx.getNumber())

print(myobjectx.number)


In [ ]:
class Animal:
    def eat(self):
        print("I can eat!")
    
    def sleep(self):
        print("I can sleep!")

class Dog(Animal): # extends
    
    def eat(self):
        super().eat()
        print("Dog is eating!")
        
    def bark(self):
        print("I can bark!")

dog1 = Dog()
dog1.eat()
dog1.sleep()
dog1.bark()

## Private

In [ ]:
class Computer:

    def __init__(self):
        self.__maxprice = 900

    def sell(self):
        print("Selling Price: {}".format(self.__maxprice))

    def setMaxPrice(self, price):
        self.__maxprice = price

c = Computer()
c.sell()

# change the price
c.__maxprice = 1000
c.sell()

# using setter function
c.setMaxPrice(1000)
c.sell()

Here, we have tried to modify the value of __maxprice outside of the class. However, since __maxprice is a private variable, this modification is not seen on the output.

As shown, to change the value, we have to use a setter function i.e setMaxPrice() which takes price as a parameter.

## Polymorphism

In [ ]:
class Polygon:
    # method to render a shape
    def render(self):
        print("Rendering Polygon...")

class Square(Polygon):
    # renders Square
    def render(self):
        print("Rendering Square...")

class Circle(Polygon):
    # renders circle
    def render(self):
        print("Rendering Circle...")
    
# create an object of Square
s1 = Square()
s1.render()

# create an object of Circle
c1 = Circle()
c1.render()

## Multiple Inheritance

Method Resolution specifies that methods should be inherited from the leftmost superclass first, so info() of SuperClass1 is called rather than that of SuperClass2.

In [ ]:
class SuperClass1:
    def info(self):
        print("Super Class 1 method called")

class SuperClass2:
    def info(self):
        print("Super Class 2 method called")

class Derived(SuperClass1, SuperClass2):
    pass

d1 = Derived()
d1.info()  

# Output: "Super Class 1 method called"

## Operator Overloading

Function	Description
- __init__()	initialize the attributes of the object
- __str__()	returns a string representation of the object
- __len__()	returns the length of the object
- __add__()	adds two objects
- __call__()	call objects of the class like a normal function

Operator	Expression	Internally
- Addition	p1 + p2	p1.__add__(p2)
- Subtraction	p1 - p2	p1.__sub__(p2)
- Multiplication	p1 * p2	p1.__mul__(p2)
- Power	p1 ** p2	p1.__pow__(p2)
- Division	p1 / p2	p1.__truediv__(p2)
- Floor Division	p1 // p2	p1.__floordiv__(p2)
- Remainder (modulo)	p1 % p2	p1.__mod__(p2)
- Bitwise Left Shift	p1 << p2	p1.__lshift__(p2)
- Bitwise Right Shift	p1 >> p2	p1.__rshift__(p2)
- Bitwise AND	p1 & p2	p1.__and__(p2)
- Bitwise OR	p1 | p2	p1.__or__(p2)
- Bitwise XOR	p1 ^ p2	p1.__xor__(p2)
- Bitwise NOT	~p1	p1.__invert__()



Operator	Expression	Internally
- Less than	p1 < p2	p1.__lt__(p2)
- Less than or equal to	p1 <= p2	p1.__le__(p2)
- Equal to	p1 == p2	p1.__eq__(p2)
- Not equal to	p1 != p2	p1.__ne__(p2)
- Greater than	p1 > p2	p1.__gt__(p2)
- Greater than or equal to	p1 >= p2	p1.__ge__(p2)

In [ ]:
class Point:
    def __init__(self, x=0, y=0):
        self.x = x
        self.y = y

    def __str__(self):
        return "({0},{1})".format(self.x, self.y)

    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        return Point(x, y)


p1 = Point(1, 2)
p2 = Point(2, 3)

print(str(p1))

print(p1+p2)

## Iterator

In [ ]:
class PowTwo:
    """Class to implement an iterator
    of powers of two"""

    def __init__(self, max=0):
        self.max = max

    def __iter__(self):
        self.n = 0
        return self

    def __next__(self):
        if self.n <= self.max:
            result = 2 ** self.n
            self.n += 1
            return result
        else:
            raise StopIteration


# create an object
numbers = PowTwo(3)

for i in numbers:
    print(i)

# create an iterable from the object
i = iter(numbers)

# Using next to get to the next iterator element
print(next(i)) # prints 1
print(next(i)) # prints 2
print(next(i)) # prints 4
print(next(i)) # prints 8
print(next(i)) # raises StopIteration exception

# Dictionary

vgl. HashMap
A dictionary is a data type similar to arrays, but works with keys and values instead of indexes. Each value stored in a dictionary can be accessed using a key, which is any type of object (a string, a number, a list, etc.) instead of using its index to address it.

In [ ]:
phonebook = {}
phonebook["John"] = 938477566
phonebook["Jack"] = 938377264
phonebook["Jill"] = 947662781
print(phonebook)

# NumPy
numpy arrays are great alternatives to Python Lists. Some of the key advantages of Numpy arrays are that they are fast, easy to work with, and give users the opportunity to perform calculations across entire arrays.

In [31]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [32]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [33]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
a = np.array(42)
print(a.ndim)
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(b.ndim)

0
2


In [35]:
arr = np.array([1,2,3,4])
print(arr[2] + arr[3])
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr[1, 2])

7
6


## Slicing

In [36]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[2:])

[2 3 4 5]
[3 4 5 6 7]


In [37]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 2])
print(arr[1, 1:4])

[3 8]
[7 8 9]


## Copy vs. Views

In [38]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [39]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
x[2] = 13
print(arr)
print(x)

[42  2 13  4  5]
[42  2 13  4  5]


## Shape

In [40]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr.shape)

(2, 4)


In [41]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [42]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [43]:
arr = np.array([[1,2,3],[4,5,6]])
newarray = arr.reshape(-1)
print(newarray)

[1 2 3 4 5 6]


## Join

In [44]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1, arr2), axis = 1)
print(arr)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


## Split

In [45]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[1])

[array([1, 2]), array([3, 4]), array([5, 6])]
[3 4]


In [46]:
arr = np.array([[1,2], [3,4],[5,6],[7,8],[9,10], [11,12]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


## Subsetting

In [50]:
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

np_height = np.array(height)
np_weight = np.array(weight)
bmi = np_weight / np_height ** 2

print(bmi)

print(bmi > 25)
print(bmi[bmi > 25])

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]
[False  True  True  True False  True]
[27.88755755 28.75558507 25.48723993 25.84368152]


# Bsp


In [51]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])
print(arr.shape)
print(arr[0:2, ::2])

(2, 10)
[[ 1  3  5  7  9]
 [11 13 15 17 19]]
